spring:
  application:
    name: retention-frontend
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

server:
  port: ${PORT:3000}
  servlet:
    context-path: /

# 로깅 설정
logging:
  level:
    com.retention.frontend: ${LOG_LEVEL:INFO}
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# 백엔드 API 설정
api:
  backend:
    base-url: ${BACKEND_API_URL:http://localhost:8000}
    timeout: 5000
  
  postgrest:
    base-url: ${POSTGREST_API_URL:http://localhost:3001}
    timeout: 5000

# CORS 설정
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: true

